-- definitions/acp_variance_explained.sqlx
config {
    type: "table",
    description: "Visualisation des composantes principales et leur variance expliquée",
    database: "financial-data-storage",
    schema: "DJI_Ind_Tech",
    dependencies: ["modele_acp"]
}

SELECT 
    principal_component_id,
    explained_variance_ratio,
    cumulative_explained_variance_ratio
FROM ML.PRINCIPAL_COMPONENT_INFO(MODEL `financial-data-storage.DJI_Ind_Tech.modele_acp`)
ORDER BY principal_component_id